export const SliderData = [
  {
    index: 0,
    id: '01',
    image: `url('/assets/img/wfhLargerImage.jpg')`,
    title: 'Work from Home',
    description: `Help your employees stay productive coast to coast.`,
    call: 'Wfh',
    video: '/assets/videos/Work-From-Home.mp4',
    status: '2020',
    analyticID: 'exp-ctd-wfh'
  },
  {
    index: 1,
    id: '02', 
    image: `url('/assets/img/Corporate-Solutions.png')`,
    title: 'Corporate Solutions',
    description: `Everything needed for the modern office.`,
    call: 'Corporate',
    video: '/assets/videos/Corporate.mp4',
    status: '2020',
    analyticID: 'exp-ctd-corporate'
  },
  {
    index: 2,
    id: '03',
    image: `url('/assets/img/mainBg.png')`,
    title: 'Continued Innovation',
    description: `Pushing the boundaries of innovation and experience.`,
    call: 'Innovation',
    video: '/assets/videos/Innovation.mp4',
    status: '2020',
    analyticID: 'exp-ctd-innovation'
  },
  {
    index: 3,
    id: '04',
    image: `url('/assets/img/Redefining-Learning-Spaces.png')`,
    title: 'Education',
    description: `Designed to meet the spectrum of student and educator needs.`,
    call: 'Education',
    video: '/assets/videos/EducationDesktop.mp4',
    status: '2020',
    analyticID: 'exp-ctd-education'
  },
  {
    index: 4,
    id: '05',
    image: `url('/assets/img/Next-Gen-Control-Room.png')`,
    title: 'Control Room',
    description: `The highest definition in the delivery of mission critical content.`,
    call: 'Control',
    video: '/assets/videos/ControlRoom.mp4',
    status: '2020',
    analyticID: 'exp-ctd-control'
  },
  {
    index: 5,
    id: '06',
    image: `url('/assets/img/Outdoor.jpg')`,
    title: 'Outdoor',
    description: `The leader in out of home signage solutions.`,
    call: 'Outdoor',
    video: '/assets/videos/Outdoor.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-outdoor'
  },
  {
    index: 6,
    id: '07',
    image: `url('/assets/img/FlagshipStore.jpg')`,
    title: 'Luxury Flagship Store',
    description: `Maximizing curb appeal on main street and in the mall.`,
    call: 'l_flagship',
    video: '/assets/videos/Flagship.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-flagship'
  },
  {
    index: 7,
    id: '08',
    image: `url('/assets/img/FastFood.jpg')`,
    title: 'Fast Food Restaurant',
    description: `Accelerating service with quality and clarity.`,
    call: 'l_fastfood',
    video: '/assets/videos/FastFood.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-fastfood'
  },
  {
    index: 8,
    id: '09',
    image: `url('/assets/img/DriveThruClinic.jpg')`,
    title: 'Drive Thru Clinic',
    description: `Innovation to optimize visitor experience.`,
    call: 'l_clinic',
    video: '/assets/videos/DriveThruClinic.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-clinic'
  },
  {
    index: 9,
    id: '10',
    image: `url('/assets/img/HospitalLobby.jpg')`,
    title: 'Hospital Lobby',
    description: `The latest in lobby signage and display.`,
    call: 'HospitalLobby',
    video: '/assets/videos/Hospital-Lobby.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-hospitallobby'
  },
  {
    index: 10,
    id: '11',
    image: `url('/assets/img/Supermarket.jpg')`,
    title: 'Grocery Store',
    description: `The next generation of grocery signage and engagement.`,
    call: 'Supermarket',
    video: '/assets/videos/Supermarket.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-supermarket'
  },
  {
    index: 11,
    id: '12',
    image: `url('/assets/img/Hotel.jpg')`,
    title: 'Hotel Room',
    description: `In-room experience amplified`,
    call: 'HotelRoom',
    video: '/assets/videos/LGHomePageWalkThru.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-hotelroom'
  },
  {
    index: 12,
    id: '13',
    image: `url('/assets/img/HomeCinema.jpg')`,
    title: 'Home Cinema',
    description: `The ultimate viewing in experience in the comfort of your home.`,
    call: 'HomeMovies',
    video: '/assets/videos/HomeCinema.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-homemovies'
  },
  {
    index: 13,
    id: '14',
    image: `url('/assets/img/Transportation.jpg')`,
    title: 'Metro',
    description: `Imagining the future of connected transportation.`,
    call: 'Metro',
    video: '/assets/videos/Metro.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-metro'
  },
  {
    index: 14,
    id: '15',
    image: `url('/assets/img/Cinema.jpg')`,
    title: 'Cinema',
    description: `The ultimate viewing experience.`,
    call: 'Cinema',
    video: '/assets/videos/Cinema.mp4',
    status: 'NEW',
    analyticID: 'exp-ctd-cinema'
  },
];
