export const ProductsData = [
  {
    index: 0,
    pid: 'lsab009',
    image: `url('./assets/img/products/LSAB/LSAB-SERIES-LG MAGNIT-NEW.jpg')`,
    pname: 'LG MAGNIT',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Home Cinema', 'Control Room'],
    pdata: './Global/pdata/lsab009.json',
    pscall: ['HomeMovies_lsab009', 'Control_lsab009'],
  },
  {
    index: 1,
    pid: '15z90n-n.aps9u1',
    image: `url('./assets/img/products/15Z90N/15Z90N-LG-GRAM-final(wfh).jpg')`,
    pname: 'LG GRAM',
    pcategory: 'IT Products',
    ptype: 'Laptops',
    pspace: ['Corporate'],
    pdata: './Global/pdata/15z90n-n.aps9u1.json',
    pscall: ['Corporate_15z90']
  },
  {
    index: 2,
    pid: '27qn880-b',
    image: `url('./assets/img/products/27qn880-b/MNT-27QN880-01-2-LG-QHD-Ergo-D.webp')`,
    pname: 'LG QHD Monitor Ergo',
    pcategory: 'IT Products',
    ptype: 'PC Monitors',
    pspace: ['Home Office'],
    pdata: './Global/pdata/27qn880-b.json',
    pscall: ['HomeOffice_27qn880-b']
  },
  {
    index: 3,
    pid: 'gsca046-gn',
    image: `url('./assets/img/products/gsca046-gn/GSCA-SERIES,-GSCD-SERIES-OUTDOOR-LED-SIGNAGE(OUTD).jpg')`,
    pname: 'OUTDOOR LED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Outdoor LED Displays',
    pspace: ['Outdoor'],
    pdata: './Global/pdata/gsca046-gn.json',
    pscall: ['Outdoor_gsca046-gn']
  },
  {
    index: 4,
    pid: 'lbs060da4d',
    image: `url('./assets/img/products/lbs060da4d/LBS-OUTDOOR-SERIES-OUTDOOR-LED-SIGNAGE(OUTD).jpg')`,
    pname: 'OUTDOOR LED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Outdoor LED Displays',
    pspace: ['Outdoor'],
    pdata: './Global/pdata/lbs060da4d.json',
    pscall: ['Outdoor_lbs060da4d']
  },
  {
    index: 5,
    pid: '55ew5tf-a',
    image: `url('./assets/img/products/55EW5TF-A/55EW5TF-A-55-TRANSPARENT-OLED-TOUCHSCREEN-OPEN-FRAME-final.jpg')`,
    pname: 'TRANSPARENT OLED TOUCH SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'OLED Displays',
    pspace: ['Metro', 'Innovation'],
    pdata: './Global/pdata/55ew5tf-a.json',
    pscall: ['Metro_55ew5tf-a','Innovation_55ew5tf-a']
  },
  {
    index: 6,
    pid: '55ef5g-l',
    image: `url('./assets/img/products/55ef5g-l/55EF5G-L-FLEXIBLE-CURVED-OPEN-FRAME-OLED-SIGNAGE(METRO).jpg')`,
    pname: 'FLEXIBLE CURVED OPEN FRAME OLED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'OLED Displays',
    pspace: ['Metro'],
    pdata: './Global/pdata/55ef5g-l.json',
    pscall: ['Metro_55ef5g-l']
  },
  {
    index: 7,
    pid: 'lat140',
    image: `url('./assets/img/products/lat140/LAT-SERIES-LG-LED-TRANSPARENT(LFS).jpg')`,
    pname: 'LG LED TRANSPARENT',
    pcategory: 'Commercial Displays',
    ptype: 'Transparent LED Film',
    pspace: ['Luxury Flagship Store'],
    pdata: './Global/pdata/lat140.json',
    pscall: ['l_flagship_lat140']
  },
  {
    index: 8,
    pid: '75xs4g-b',
    image: `url('./assets/img/products/75xs4g-b/75XS4G-WINDOW-FACING-DISPLAY(LFS).jpg')`,
    pname: 'WINDOW FACING DISPLAY',
    pcategory: 'Commercial Displays',
    ptype: 'High Bright Displays',
    pspace: ['Luxury Flagship Store'],
    pdata: './Global/pdata/75xs4g-b.json',
    pscall: ['l_flagship_75xs4g-b']
  },
  {
    index: 9,
    pid: '49xe4f-m',
    image: `url('./assets/img/products/49xe4f-m/XE4F-SERIES-IP-RATED-OUTDOOR-DISPLAY(FAST2).jpg')`,
    pname: 'IP-RATED OUTDOOR DISPLAY',
    pcategory: 'Commercial Displays',
    ptype: 'High Bright Displays',
    pspace: ['Fast Food Drive Thru', 'Outdoor', 'Drive Thru Clinic'],
    pdata: './Global/pdata/49xe4f-m.json',
    pscall: ['l_fastfood_49xe4f-m1','Outdoor_49xe4f-m1', 'l_clinic_49xe4f-m1']
  },
  {
    index: 10,
    pid: '49xs4f-b',
    image: `url('./assets/img/products/49xs4f-b/XS4F-SERIES-HIGH-BRIGHTNESS-WINDOW-FACING-(FASTF3).jpg')`,
    pname: 'HIGH BRIGHTNESS WINDOW FACING',
    pcategory: 'Commercial Displays',
    ptype: 'High Bright Displays',
    pspace: ['Fast Food Drive Thru', 'Supermarket'],
    pdata: './Global/pdata/49xs4f-b.json',
    pscall: ['l_fastfood_49xs4f-b','Supermarket_49xs4f-b']
  },
  {
    index: 11,
    pid: '32ta3e-b',
    image: `url('./assets/img/products/32ta3e-b/TA3E-SERIES-BUILT-IN-INTERACTIVE-TOUCH-SIGNAGE(HL).jpg')`,
    pname: 'BUILT-IN TOUCH SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Touch Screens',
    pspace: ['Supermarket'],
    pdata: './Global/pdata/32ta3e-b.json',
    pscall: ['Supermarket_32ta3e-b']
  },
  {
    index: 12,
    pid: '43uh5f-h',
    image: `url('./assets/img/products/43uh5f-h/UH5F-H-SERIES-UHD-SIGNAGE-(SUPERM2).jpg')`,
    pname: 'UHD SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'UHD/FHD LCD Displays',
    pspace: ['Supermarket'],
    pdata: './Global/pdata/43uh5f-h.json',
    pscall: ['Supermarket_43uh5f-h']
  },
  {
    index: 13,
    pid: '86bh5f-b',
    image: `url('./assets/img/products/86bh5f-b/86BH5F-86”-ULTRA-STRETCH.JPG')`,
    pname: '86” ULTRA STRETCH',
    pcategory: 'Commercial Displays',
    ptype: 'Ultra Stretch',
    pspace: ['Supermarket'],
    pdata: './Global/pdata/86bh5f-b.json',
    pscall: ['Supermarket_86bh5f-b']
  },
  {
    index: 14,
    pid: '32ta3e-b.aus',
    image: `url('./assets/img/products/32ta3e-b/TA3E-SERIES-BUILT-IN-INTERACTIVE-TOUCH-SIGNAGE(HL).jpg')`,
    pname: 'BUILT-IN INTERACTIVE TOUCH SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Touch Screens',
    pspace: ['Hospital Lobby', 'Supermarket'],
    pdata: './Global/pdata/32ta3e-b.aus.json',
    pscall: ['HospitalLobby_32ta3e-b','Supermarket_32ta3e-b']
  },
  {
    index: 15,
    pid: '88bh7f-b',
    image: `url('./assets/img/products/88bh7f/88BH7F-88”-ULTRA-STRETCH-final.jpg')`,
    pname: '88” ULTRA STRETCH',
    pcategory: 'Commercial Displays',
    ptype: 'Ultra Stretch',
    pspace: ['Hospital Lobby', 'Corporate'],
    pdata: './Global/pdata/88bh7f-b.json',
    pscall: ['HospitalLobby_88bh7f-b','Corporate_88bh7f-b']
  },
  {
    index: 16,
    pid: 'lsca029',
    image: `url('./assets/img/products/lsca029/LSCA-SERIES-INDOOR-LED-SIGNAGE(HL).jpg')`,
    pname: 'INDOOR LED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Hospital Lobby'],
    pdata: './Global/pdata/lsca029.json',
    pscall: ['HospitalLobby_lsca029']
  },
  {
    index: 17,
    pid: '49ut761h',
    image: `url('./assets/img/products/49ut761h/UT761H-SERIES-NANOCELL-TV-FOR-HOSPITALITY(HR).jpg')`,
    pname: 'NANOCELL TV FOR HOSPITALITY',
    pcategory: 'Hospitality Displays',
    ptype: 'Hotel TVs',
    pspace: ['Hotel Guest Room'],
    pdata: './Global/pdata/49ut761h.json',
    pscall: ['HotelRoom_49ut761h']
  },
  {
    index: 18,
    pid: '65ws960h0ud',
    image: `url('./assets/img/products/65ws960h0ud/WS960H-OLED-TV-FOR-HOSPITALITY(HR).jpg')`,
    pname: 'OLED TV FOR HOSPITALITY',
    pcategory: 'Hospitality Displays',
    ptype: 'Hotel TVs',
    pspace: ['Hotel Guest Room'],
    pdata: './Global/pdata/65ws960h0ud.json',
    pscall: ['HotelRoom_65ws960h0ud']
  },
  {
    index: 19,
    pid: '49uh7f-b',
    image: `url('./assets/img/products/49uh7f-b/65UH7F_final.jpg')`,
    pname: 'UHD SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'UHD/FHD LCD Displays',
    pspace: ['Hospital Lobby', 'Corporate', 'Supermarket', 'Drive Thru Clinic'],
    pdata: './Global/pdata/49uh7f-b.json',
    pscall: ['HospitalLobby_49uh7f-b','Corporate_49uh7f-b', 'Supermarket_49uh7f-b','l_clinic_49uh7f-b']
  },
  {
    index: 20,
    pid: 'lsaa012',
    image: `url('./assets/img/products/LSAA/ALL-IN-ONE-SERIES-(LAAF)-130-ALL-IN-ONE-LED-SCREEN-final.jpg')`,
    pname: 'LG LED BLOC',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Corporate'],
    pdata: './Global/pdata/lsaa012.json',
    pscall: ['Corporate_lsaa012']
  },
  {
    index: 21,
    pid: '86tn3f-b',
    image: `url('./assets/img/products/86TN3F/86TN3F-B.jpg')`,
    pname: '86" IN-CELL TOUCHSCREEN SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Touch Screens',
    pspace: ['Corporate'],
    pdata: './Global/pdata/86tn3f-b.json',
    pscall: ['Corporate_86tn3f-b']
  },
  {
    index: 22,
    pid: 'laa015f',
    image: `url('./assets/img/products/LAA015F/Laa015F.jpg')`,
    pname: '130" ALL-IN-ONE LED SCREEN',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Corporate'],
    pdata: './Global/pdata/laa015f.json',
    pscall: ['Corporate_laa015f']
  },
  {
    index: 23,
    pid: '34bl650-b',
    image: `url('./assets/img/products/34BL650/34BL650-34-ULTRAWIDE-MONITOR-final.jpg')`,
    pname: '34" ULTRAWIDE MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraWide Monitors',
    pspace: ['Work From Home'],
    pdata: './Global/pdata/34bl650-b.json',
    pscall: ['Wfh_34bl650-b']
  },
  {
    index: 24,
    pid: '34cn650n-6a',
    image: `url('./assets/img/products/34CN650N/34CN650N-34-ULTRAWIDE-FHD-ALL-IN-ONE-THIN CLIENT-final.jpg')`,
    pname: '34" ULTRAWIDE FHD ALL-IN-ONE THIN CLIENT',
    pcategory: 'IT Products',
    ptype: 'UltraWide Monitors',
    pspace: ['Work From Home'],
    pdata: './Global/pdata/34cn650n-6a.json',
    pscall: ['Wfh_34cn650n-6a']
  },
  {
    index: 25,
    pid: '86ut640s0ua',
    image: `url('./assets/img/products/86UT640S/UT640S-SERIES-UHD-SMART-SIGNAGE-final.jpg')`,
    pname: 'UHD SMART SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'UHD/FHD LCD Displays',
    pspace: ['Education'],
    pdata: './Global/pdata/86ut640s0ua.json',
    pscall: ['Education_86ut640s0ua_1']
  },
  {
    index: 26,
    pid: 'laeb015',
    image: `url('./assets/img/products/LAEB/ALL-IN-ONE-SERIES-(LAEB)-136-ALL-IN-ONE-LED-SCREEN-final.jpg')`,
    pname: '136" ALL-IN-ONE LED SCREEN',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Education'],
    pdata: './Global/pdata/laeb015.json',
    pscall: ['Education_laeb015']
  },
  {
    index: 27,
    pid: '38gn95b-b',
    image: `url('./assets/img/products/38GN95B/38GN95B-38-ULTRAGEAR-GAMING-MONITOR-final.jpg')`,
    pname: '38" ULTRAGEAR GAMING MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraGear Monitors',
    pspace: ['Education'],
    pdata: './Global/pdata/38gn95b-b.json',
    pscall: ['Education_38gn95b-b']
  },
  {
    index: 28,
    pid: '27gn75b-b',
    image: `url('./assets/img/products/27GN75B/27GN75B-27-ULTRAGEAR-GAMING-MONITOR-final.jpg')`,
    pname: '27" ULTRAGEAR GAMING MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraGear Monitors',
    pspace: ['Education'],
    pdata: './Global/pdata/27gn75b-b.json',
    pscall: ['Education_27gn75b-b']
  },
  {
    index: 29,
    pid: '65tr3bf-b',
    image: `url('./assets/img/products/65tr3bf-b/TR3BF-INTERACTIVE-DIGITAL-BOARD-final.jpg')`,
    pname: 'INTERACTIVE DIGITAL BOARD',
    pcategory: 'Commercial Displays',
    ptype: 'Touch Screens',
    pspace: ['Education'],
    pdata: './Global/pdata/65tr3bf-b.json',
    pscall: ['Education_65tr3bf-b']
  },
  {
    index: 30,
    pid: '27bl650c-b',
    image: `url('./assets/img/products/27BL650C-B/27BL650C-B-27-FULL-HD-IPS-MONITOR-final.jpg')`,
    pname: '27" FULL HD IPS MONITOR',
    pcategory: 'IT Products',
    ptype: 'PC Monitors',
    pspace: ['Education'],
    pdata: './Global/pdata/27bl650c-b.json',
    pscall: ['Education_27bl650c-b']
  },
  {
    index: 31,
    pid: '29bn650-b',
    image: `url('./assets/img/products/29BN650-B/29BN650-B-29-ULTRAWIDE-FLAT-MONITOR-final.jpg')`,
    pname: '29" ULTRAWIDE FLAT MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraWide Monitors',
    pspace: ['Education'],
    pdata: './Global/pdata/29bn650-b.json',
    pscall: ['Education_29bn650-b']
  },
  {
    index: 32,
    pid: '55svh7f',
    image: `url('./assets/img/products/55SVH7PF/55SVH7F-0.44MM-EVEN-BEZEL-VIDEO-WALL-WITH-SMART-CALIBRATION-final.jpg')`,
    pname: '0.44MM EVEN BEZEL VIDEO WALL WITH SMART CALIBRATION',
    pcategory: 'Commercial Displays',
    ptype: 'Video Walls',
    pspace: ['Control Room'],
    pdata: './Global/pdata/55svh7f.json',
    pscall: ['Control_55svh7f']
  },
  {
    index: 33,
    pid: '49bl95c-w',
    image: `url('./assets/img/products/49BL95C-W/49BL95C-W-49-329-CURVED-ULTRAWIDE-DUAL-QHD-IPS-MONITOR(2)-final.png')`,
    pname: '49" 32:9 CURVED ULTRAWIDE DUALL QHD IPS MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraWide Monitors',
    pspace: ['Control Room'],
    pdata: './Global/pdata/49bl95c-w.json',
    pscall: ['Control_49bl95c-w']
  },
  {
    index: 34,
    pid: '32bn88u-b',
    image: `url('./assets/img/products/32BN88U-B/32BN88U-B-32-ULTRA-HD-MONITOR-WITH-ERGO-STAND-Final.jpg')`,
    pname: '29" ULTRAWIDE FLAT MONITOR',
    pcategory: 'IT Products',
    ptype: 'UHD Monitors',
    pspace: ['Control Room'],
    pdata: './Global/pdata/32bn88u-b.json',
    pscall: ['Control_32bn88u-b']
  },
  {
    index: 35,
    pid: 'bu50nst',
    image: `url('./assets/img/products/PJT-BU50N/BU50NST-PROBEAM-LASER-PROJECTOR-final.jpg')`,
    pname: 'PROBEAM LASER PROJECTOR',
    pcategory: 'IT Products',
    ptype: 'Projectors',
    pspace: ['Control Room'],
    pdata: './Global/pdata/bu50nst.json',
    pscall: ['Control_bu50nst']
  },
  {
    index: 36,
    pid: '35bn75c-b',
    image: `url('./assets/img/products/35BN75C-B/35BN75C-B-35-CURVED-ULTRAWIDE™-MONITOR-final.jpg')`,
    pname: '35" CURVED ULTRAWIDE™ MONITOR',
    pcategory: 'IT Products',
    ptype: 'UltraWide Monitors',
    pspace: ['Control Room'],
    pdata: './Global/pdata/35bn75c-b.json',
    pscall: ['Control_35bn75c-b']
  },
  {
    index: 37,
    pid: '55xs4f-b',
    image: `url('./assets/img/products/55XS4F/55XS4F-HIGH-BRIGHTNESS-INDOOR-WINDOW-FACING-SIGNAGE-final.jpg')`,
    pname: 'HIGH BRIGHTNESS INDOOR WINDOW FACING SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'High Bright Displays',
    pspace: ['Innovation'],
    pdata: './Global/pdata/55xs4f-b.json',
    pscall: ['Innovation_55xs4f-b']
  },
  {
    index: 38,
    pid: 'gscc080-gn',
    image: `url('./assets/img/products/GSCC/GSCC-SERIES-ESSENTIAL-SERIES-OUTDOOR-LED-SIGNAGE-final.jpg')`,
    pname: 'ESSENTIAL SERIES OUTDOOR LED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Outdoor LED Displays',
    pspace: ['Innovation'],
    pdata: './Global/pdata/gscc080-gn.json',
    pscall: ['Innovation_gscc080-gn']
  },
  {
    index: 39,
    pid: 'lscb015-gk',
    image: `url('./assets/img/products/LSCB/LSCB-SERIES-INDOOR-DIRECT-VIEW-LED-SIGNAGE-final.jpg')`,
    pname: 'INDOOR DIRECT VIEW LED SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Indoor LED Displays',
    pspace: ['Innovation'],
    pdata: './Global/pdata/lscb015-gk.json',
    pscall: ['Innovation_lscb015-gk']
  },
  {
    index: 40,
    pid: '55ew5f-a',
    image: `url('./assets/img/products/55ew5f-a/55EW5F-A.jpg')`,
    pname: '55" TRANSPARENT OLED DIGITAL SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'OLED Displays',
    pspace: ['Innovation'],
    pdata: './Global/pdata/55ew5f-a.json',
    pscall: ['Innovation_55ew5f-a']
  },
  {
    index: 41,
    pid: 'lat240dt1',
    image: `url('./assets/img/products/LAT240/LAT240-TRANSPARENT-COLOR-LED-FILM-final.jpg')`,
    pname: 'TRANSPARENT COLOR LED FILM',
    pcategory: 'Commercial Displays',
    ptype: 'Transparent LED Film',
    pspace: ['Innovation'],
    pdata: './Global/pdata/lat240dt1.json',
    pscall: ['Innovation_lat240dt1']
  },
  {
    index: 42,
    pid: '86bh5c',
    image: `url('./assets/img/products/86BH5C/86BH5C-86-ULTRA-STRETCH-SIGNAGE-final.jpg')`,
    pname: '86" ULTRA STRETCH SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'Ultra Stretch',
    pspace: ['Innovation'],
    pdata: './Global/pdata/86bh5c.json',
    pscall: ['Innovation_86bh5c']
  },
  {
    index: 43,
    pid: '55ef5f-l.aus',
    image: `url('./assets/img/products/55EF5F-L/55EF5F-FLEXIBLE,-CURVABLE-OPEN-FRAME-OLED-SMART-SIGNAGE-final.jpg')`,
    pname: 'FLEXIBLE, CURVABLE OPEN FRAME OLED SMART SIGNAGE',
    pcategory: 'Commercial Displays',
    ptype: 'OLED Displays',
    pspace: ['Innovation'],
    pdata: './Global/pdata/55ef5f-l.aus.json',
    pscall: ['Innovation_55ef5f-l']
  },
];
